// <auto-generated />
namespace StudyPortal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Initialsetup : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Initialsetup));
        
        string IMigrationMetadata.Id
        {
            get { return "201701151727042_Initial set up"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
